/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Lista;
import Funciones.Cobertura;
import static Interfaces.Inicio.gestionApp;
import static Interfaces.Inicio.redGrafo;
import static Interfaces.Inicio.valorT;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Moises Liota
 */
public class Coberturas extends javax.swing.JFrame {

    DefaultComboBoxModel modelEstaciones = new DefaultComboBoxModel();
    private String busqueda = "";

    public Coberturas() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        tiposRecorridos.add(busqBFS);
        tiposRecorridos.add(busqDFS);

        this.llenarComboBoxEstaciones();
    }

    private void llenarComboBoxEstaciones() {
        Lista nombres = gestionApp.nombresEstacionesSucursal(redGrafo);
        for (int i = 0; i < nombres.getSize(); i++) {
            modelEstaciones.addElement(nombres.getValor(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiposRecorridos = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        estaciones = new javax.swing.JComboBox<>();
        busqBFS = new javax.swing.JRadioButton();
        busqDFS = new javax.swing.JRadioButton();
        realizarCobertura = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Revisar Coberturas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        estaciones.setModel(modelEstaciones);
        jPanel1.add(estaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 260, -1));

        busqBFS.setText("BFS");
        busqBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqBFSActionPerformed(evt);
            }
        });
        jPanel1.add(busqBFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        busqDFS.setText("DFS");
        busqDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqDFSActionPerformed(evt);
            }
        });
        jPanel1.add(busqDFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        realizarCobertura.setText("Revisar Cobertura");
        realizarCobertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarCoberturaActionPerformed(evt);
            }
        });
        jPanel1.add(realizarCobertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 270, -1));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busqDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqDFSActionPerformed
       busqueda = "DFS";
    }//GEN-LAST:event_busqDFSActionPerformed

    private void realizarCoberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarCoberturaActionPerformed
        Cobertura cobertura = new Cobertura(redGrafo, valorT);
        String origen = (String) estaciones.getSelectedItem();
        if("BFS".equals(busqueda)){
            cobertura.realizarBusquedaBFS(redGrafo.buscar(origen));
        }else if("DFS".equals(busqueda)){
            cobertura.realizarBusquedaDFS(redGrafo.buscar(origen));
        }else{
            JOptionPane.showMessageDialog(null, "Debes seleccionar una opcion para recorrer");
        } 
    }//GEN-LAST:event_realizarCoberturaActionPerformed

    private void busqBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqBFSActionPerformed
        busqueda = "BFS";
    }//GEN-LAST:event_busqBFSActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Menu menu =new Menu();
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coberturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coberturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coberturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coberturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coberturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton busqBFS;
    private javax.swing.JRadioButton busqDFS;
    private javax.swing.JComboBox<String> estaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton realizarCobertura;
    private javax.swing.ButtonGroup tiposRecorridos;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
