/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Lista;
import Funciones.GestionSucursal;
import static Interfaces.Inicio.gestionApp;
import static Interfaces.Inicio.redGrafo;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class GestionSucursales extends javax.swing.JFrame {

    DefaultComboBoxModel comboEstaciones = new DefaultComboBoxModel();
    private GestionSucursal gestionS  = new GestionSucursal(redGrafo);
    DefaultComboBoxModel comboSucursales = new DefaultComboBoxModel();
    

    public GestionSucursales() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        Lista nombresSinSucursal = gestionApp.nombresEstacionesSinSucursal(redGrafo);
        if(!nombresSinSucursal.EsVacio()){
            for (int i = 0; i < nombresSinSucursal.getSize(); i++) {
                comboEstaciones.addElement(nombresSinSucursal.getValor(i));
            }
        }
        
        Lista nombresConSucursal = gestionApp.nombresEstacionesSucursal(redGrafo);
        if(!nombresConSucursal.EsVacio()){
            for (int i = 0; i < nombresConSucursal.getSize(); i++) {
                comboSucursales.addElement(nombresConSucursal.getValor(i));
            }
        }
        
        sucursales.setText(gestionS.nombres());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        estacionesSinSucursal = new javax.swing.JComboBox<>();
        addSucursal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        estacionesSucursal = new javax.swing.JComboBox<>();
        eliminarSucursal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sucursales = new javax.swing.JTextArea();
        volverMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Agregar una sucursal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        estacionesSinSucursal.setModel(comboEstaciones);
        jPanel1.add(estacionesSinSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, -1));

        addSucursal.setText("Agregar Sucursal");
        addSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(addSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, -1));

        jLabel2.setText("Seleccione la estacion para agregar la suscursal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setText("Seleccione la sucursal a eliminar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        estacionesSucursal.setModel(comboSucursales);
        jPanel1.add(estacionesSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 220, -1));

        eliminarSucursal.setText("Eliminar Sucursal");
        eliminarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 220, -1));

        jLabel4.setText("Sucursales");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel5.setText("Propuesta:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        sucursales.setColumns(20);
        sucursales.setRows(5);
        jScrollPane1.setViewportView(sucursales);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 230, 170));

        volverMenu.setText("Volver al Menu");
        volverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuActionPerformed(evt);
            }
        });
        jPanel1.add(volverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSucursalActionPerformed
       String nombreParada = (String) estacionesSinSucursal.getSelectedItem();
        gestionS.colocarSucursal(nombreParada);
       JOptionPane.showMessageDialog(null, "Sucursal agregada con exito");
        
       comboEstaciones.removeAllElements();
        Lista nombresSinSucursal = gestionApp.nombresEstacionesSinSucursal(redGrafo);
        if(!nombresSinSucursal.EsVacio()){
            for (int i = 0; i < nombresSinSucursal.getSize(); i++) {
                comboEstaciones.addElement(nombresSinSucursal.getValor(i));
            }
        }
        
        comboSucursales.removeAllElements();
        Lista nombresConSucursal = gestionApp.nombresEstacionesSucursal(redGrafo);
        if(!nombresConSucursal.EsVacio()){
            for (int i = 0; i < nombresConSucursal.getSize(); i++) {
                comboSucursales.addElement(nombresConSucursal.getValor(i));
            }
        }
        
        sucursales.setText(gestionS.nombres());
        
        
    }//GEN-LAST:event_addSucursalActionPerformed

    private void eliminarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarSucursalActionPerformed
        String nombreParada = (String) estacionesSucursal.getSelectedItem();
       gestionS.eliminarSucursal(nombreParada);
       JOptionPane.showMessageDialog(null, "Sucursal eliminada con exito");
        
       comboEstaciones.removeAllElements();
        Lista nombresSinSucursal = gestionApp.nombresEstacionesSinSucursal(redGrafo);
        if(!nombresSinSucursal.EsVacio()){
            for (int i = 0; i < nombresSinSucursal.getSize(); i++) {
                comboEstaciones.addElement(nombresSinSucursal.getValor(i));
            }
        }
        
        comboSucursales.removeAllElements();
        Lista nombresConSucursal = gestionApp.nombresEstacionesSucursal(redGrafo);
        if(!nombresConSucursal.EsVacio()){
            for (int i = 0; i < nombresConSucursal.getSize(); i++) {
                comboSucursales.addElement(nombresConSucursal.getValor(i));
            }
        }
        
        sucursales.setText(gestionS.nombres());
    }//GEN-LAST:event_eliminarSucursalActionPerformed

    private void volverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuActionPerformed
        Menu menu = new Menu();
        this.dispose();
    }//GEN-LAST:event_volverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionSucursales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSucursal;
    private javax.swing.JButton eliminarSucursal;
    private javax.swing.JComboBox<String> estacionesSinSucursal;
    private javax.swing.JComboBox<String> estacionesSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea sucursales;
    private javax.swing.JButton volverMenu;
    // End of variables declaration//GEN-END:variables
}
